# Google Cloud Build configuration for automated deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/options-trading-bot:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/options-trading-bot:latest'
      - '.'
    timeout: 600s

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/options-trading-bot:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/options-trading-bot:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'options-trading-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/options-trading-bot:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '1'
      - '--min-instances'
      - '1'
      - '--port'
      - '8000'
      - '--set-env-vars'
      - 'TRADING_MODE=paper'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/options-trading-bot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/options-trading-bot:latest'

# Build timeout
timeout: 1200s

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
